### ISSUE TITLE
[Bug] When will v2 release?

### ISSUE THREAD

**Issue by jinfagang** [fayeed/dash_chat#171]
It's April now, very soon be May, when will v2 release?E

**Comment by AllenKaplan** [comment]
If you read #157 you can see @fayeed and @SebastienBtr have been busy. As they are doing this out of their goodwill, I suggest you not press them to release it. 

From what I have seen, you've asked numerous times in this repository when it will be released, but perhaps you should be asking what you can do to help since it seems you are very passionate about this project being updated and maintained 😄

**Comment by jinfagang** [comment]
@AllenKaplan Yes, I am need this project. But I don't know where to start help?
